#!/bin/bash

# swww animation settings
export SWWW_TRANSITION=grow                    # Sets the type of transition. Default is 'simple', that fades into the new image
export SWWW_TRANSITION_STEP=100                 # How fast the transition approaches the new image
export SWWW_TRANSITION_DURATION=1.5             # How long the transition takes to complete in seconds
export SWWW_TRANSITION_FPS=60                  # Frame rate for the transition effect
export SWWW_TRANSITION_ANGLE=180                # This is only used for the 'wipe' transition. It controls the angle of the wipe
export SWWW_TRANSITION_POS=0.6877,0.975         # This is only used for the 'grow','outer' transitions. It controls the center of circle
export SWWW_TRANSITION_BEZIER=.4,0.02,0.21,0.99 # bezier curve to use for the transition


# if swww is not started, start it
if ! pgrep -x "swww" >/dev/null; then
    swww init
    sleep 2
fi

if [ -z "$1" ]; then
    wallpaper=$(find $HOME/.local/share/wallhaven -type f | shuf -n 1)
elif echo "$1" | grep -q "/"; then
    wallpaper="$1"
else
    wallpaper="$HOME/.local/share/wallhaven/$1"
fi


# Set wallpaper
swww img $wallpaper

#delete old cached themes
wal -c

#generate new theme
wal -i $wallpaper