#!/bin/bash

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

# Get selected text.
SELECTED=$(wl-paste -t text/plain -p)

# Get query from user.
QUERY=$(echo "$SELECTED" | dmenu -nb "$color0" -nf "$color15" \
-sb "$color1" -sf "$color15" -fn 'JetBrains Mono:size=14' \
-p "Search on Google : " -l 1 | tr ' ' '+' | head -n 1)

# Check if query is empty.
if [[ -z "$QUERY" ]]; then
  exit 0
fi

# Search on Google using default browser.
BROWSER="brave"

"$BROWSER" "https://www.google.com/search?q=$QUERY"

exit 0
